/*
 * This source file was generated by the Gradle 'init' task
 */
package vm.buddy;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class AppTest {

    @Test
    public void testAppInitialization() {
        // Ensure the App class can be instantiated
        App classUnderTest = new App();
        assertNotNull(classUnderTest, "App should be initialized");
    }
}
